name: Github action push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    if: github.repository == 'viruskizz/42bangkok_hackathon-asia-2024'
    steps:
      - uses: actions/checkout@v4
    #   - name: Pushes to another repository
    #     id: push_directory
    #     uses: cpina/github-action-push-to-another-repository@target-branch
    #     env:
    #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #     with:
    #       source-directory: .
    #       destination-github-username: '2024-Hackathon-by-42-in-Asia'
    #       destination-repository-name: '42-Bangkok-Repository'
    #       user-email: kizzaraiva@gmail.com
    #       commit-message: See ORIGIN_COMMIT from $GITHUB_REF
    #       target-branch: main
    #   - name: Finishing
    #     run: echo "Code already push to" $DESTINATION_CLONED_DIRECTORY
      - name: Push to destination repository
        run: |
          git config --global user.email "kizzaraiva@gmail.com"
          git config --global user.name "viruskizz"
          git clone https://${{ env.ORG_NAME }}:${{ secrets.API_TOKEN_GITHUB }}@github.com/${{ env.ORG_NAME }}/destination-repo.git
          cd destination-repo
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ secrets.API_TOKEN_GITHUB }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update
          git merge ${{ env.ORIGINAL_REPO_NAME }}/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: 2024-Hackathon-by-42-in-Asia