name: Github action push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'viruskizz/42bangkok_hackathon-asia-2024'
    env:
      DIRECTORY: client_repo
      SOURCE_REPO: https://github.com/viruskizz/42bangkok_hackathon-asia-2024.git
      DESTINATION_REPO: https://github.com/2024-Hackathon-by-42-in-Asia/42-Bangkok-Repository.git
      # BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_NAME: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email "kizzaraiva@gmail.com"
          git config --global user.name "viruskizz"
          git config credential.helper store
      - name: Fetch latest changes
        run: git fetch origin
      - name: Set upstream
        run: |
            git remote add upstream https://2024-Hackathon-by-42-in-Asia:${{ secrets.API_TOKEN_GITHUB }}@github.com/2024-Hackathon-by-42-in-Asia/42-Bangkok-Repository.git
            git fetch upstream
      # - name: Merge changes
      #   run: git checkout ${{ env.BRANCH_NAME }}
      - name: Push changes to client's repo
        run: git push upstream ${{ env.BRANCH_NAME }}
